version: '3'
services:
    app:
        build: .
        ports:
            - 80:8000
        working_dir: "/mount"
        entrypoint: [ "php", "artisan", "serve", "--host=0.0.0.0" ]
        volumes:
            - ./:/mount
    #     links:
    #         - libretranslate

    # libretranslate:
    #     image: libretranslate/libretranslate
    #     environment:
    #         - LT_LOAD_ONLY=en,ko
    #         - LT_DEBUG=True
    #     ports:
    #         - "5000:5000"
